CREATE DATABASE IF NOT EXISTS taskkit;

USE taskkit;

CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    bio VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workspaces (
    uuid CHAR(36) PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    wsname VARCHAR(255) NOT NULL,
    wsdescription VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (username) REFERENCES users(username)
);